services:
  api:
    build:
      context: ./docker/server
      dockerfile: Dockerfile
    container_name: "breviswall-api"
    # restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./api:/app
      - caddy_data:/data
      - caddy_config:/config
    environment:
        - SERVER_NAME=localhost
    tty: true

volumes:
  caddy_data:
    name: "breviswall-data"
  caddy_config:
    name: "breviswall-config"
