services:
  app:
    build: .
    container_name: easy-kanban-app
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/easy-kanban
    working_dir: /usr/src/easy-kanban
    command: sh -c "composer install && composer api:generate && php -S 0.0.0.0:8000 -t public"
