services:
  app:
    build: .
    container_name: breviswall-app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/usr/src/breviswall/
    working_dir: /usr/src/breviswall/
    command: sh -c "composer install && composer api:generate && php -S ${APP_DOCKER_URL} -t public"
